name: CI Build
'on':
  pull_request:
    branches:
    - main
    - master
    - develop
  push:
    branches:
    - main
    - master
    - develop
permissions:
  contents: read
  pull-requests: read
  packages: write
  id-token: write
  security-events: write
jobs:
  ci-build:
    uses: ./.github/workflows/ci-build-reusable.yml
    with:
      services: '[{"name": "app", "build_context": ".", "dockerfile": "Dockerfile", "image": "app"}]'
      acr_registry: ${{ vars.ACR_REGISTRY }}
    secrets: inherit
